name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Read properties
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
        id: read_properties
        with:
          path: gradle.properties
          properties:
            minecraft_version mod_version archives_base_name mod_group_id
      - name: Send building message to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: github.event_name == 'push' && env.DISCORD_WEBHOOK != ''
        uses: fateyan/action-discord-notifier@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: Building mod from branch ${{ steps.get_branch.outputs.branch }}
      - run: |
          chmod +x gradlew
          ./gradlew build publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Send building message to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          BRANCH: ${{ steps.get_branch.outputs.branch }}
          MOD_GROUP: ${{ steps.read_properties.outputs.mod_group_id }}
          MOD_VERSION: ${{ steps.read_properties.outputs.mod_version }}
          ARCHIVES_BASE_NAME: ${{ steps.read_properties.outputs.archives_base_name }}
        if: github.event_name == 'push' && env.DISCORD_WEBHOOK != ''
        run: node create_url.js